### ISSUE TITLE
Dev set for es-SQuAD 1.1 and 2.0

### ISSUE THREAD

**Issue by migalkin** [ccasimiro88/TranslateAlignRetrieve#4]
Hello, 
didn't manage to find the dev sets of both 1.1 and 2.0 versions.
The [model card in the transformers repo](https://huggingface.co/mrm8488/bert-base-spanish-wwm-cased-finetuned-spa-squad2-es) reports there are at least some dev sets for 2.0 and 2.0_small versions, can we expect to see them in this repo? 
Thanks!

**Comment by ccasimiro88** [comment]
Hello,

Sure, in the next days, I'll upload to the repository the DEV sets for both the version 1.1 and 2.0.

Thanks for the interest in this project!

**Comment by ccasimiro88** [comment]
You can now find SQuAD-es dev v1.1 and v2.0 (both small and full version) in the repository: https://github.com/ccasimiro88/TranslateAlignRetrieve/commit/0848556b6b1628f103fb3f3fa9039fe5165d2913
